### PR TITLE
Add vaadin-maven-plugin

### PR DESCRIPTION
**Pull request by tarekoraby**

### CODE REVIEW

**Comment by jcgueriaud1** [comment]
It's working but in the other starter jetty is used only in a test profile so it's not in the directory profile.
Same for Vaadin, it's in a scope provided this means the application has to provide it (it should not be provided by the addon)

**Comment by tarekoraby** [comment]
> in the other starter jetty is used only in a test profile so it's not in the directory profile.

I'm not sure I understand what you mean here. In this PR, jetty isn't used in the directory profile either. 

> Same for Vaadin, it's in a scope provided this means the application has to provide it (it should not be provided by the addon)

But with `provided` scope, the developer cannot demo the addon when they run `mvn jetty:run`. I understand the concern you expressed in #170. However, I think it's better addressed by using `vaadin-core` instead of `vaadin` as a dependency (I did that in an updated commit).

**Comment by jcgueriaud1** [comment]
For jetty, I did a mistake. It doesn't matter since it's not a dependency, it's a plugin.

The only issue is the dependency with vaadin, but as you replaced it to vaadin-core. Maven should omit it as duplicate in the application (and use the vaadin version of the project).

So it's fine

**Review by jcgueriaud1 — DISMISSED** [review]

**Comment by tarekoraby** [comment]
Ah, I guess we need someone with write access to this repo to do the review.

**Comment by Artur-** [comment]
Why?

**Comment by jcgueriaud1** [comment]
This is used in this page as the add-on starting point. https://vaadin.com/start#starter-templates
But it does not contain the goal prepare-frontend so when you run it you have the default jetty page and you can test the add-on.

**Pull request merged**
