### PR TITLE
chore: Upgrade to Vaadin 24

### LINKED ISSUE #280: Create V24 branch and upgrade project to latest V24.0

### PR DESCRIPTION
**Pull request by mcollovati**
Draft branch to review changes before creating `v24` branch

Closes #280

### CODE REVIEW

**Comment by mcollovati** [comment]
My biggest concern with the actual structure is that to be able to run the demo project locally, the add-on must declare vaadin dependencies with `compile` scope instead of `provided`. Otherwise, they are not picked up by jetty and the web application does not initialize Flow server-side components.

I think we should promote the usage of `provided` scope for Vaadin dependencies, to prevent unexpected version overrides in the projects using the add-ons.

Unfortunately, I'm not particular happy with the proposed solution (using a maven property to define the scope and provide its value with profiles).
We can instruct jetty to use provided scope dependencies, but they end up in the `container` classpath, not in the webapp, so the artifacts are not scanned for annotations or SPI implementation. You can specify a pattern for jar scan, but for some reason, using this configuration, the dev-bundle is always created, even if there are no local frontend files (probably some class loading issue when trying to inspect the dev-bundle jar?).

So, any suggestions are more than welcome.

**Review by tltv — DISMISSED** [review]
One solution would be to split project into two sub modules where dependencies can have their own scopes without extra variables. But having everything in one module is a bit simpler to start with and is worth keeping. Therefore suggested solution is quite clean and points out clearly the impact of having `compile` scopes for Vaadin dependencies in the add-on package.

**Comment by mcollovati** [comment]
I recall the template for V8 add-ons had two separate modules for the add-on code and the demo/test stuff.
Maybe @mstahv and @samie have some good advice on how to better handle the provided scope in the template

**Comment by samie** [comment]
Yes, the project structure was similar to Maven multi-module. We had the idea to move back to that kind of structure but since it requires more re-factoring and end-to-end testing, we haven't got that far. Would now be the right time? 

Following the "evergreen" thinking it makes sense to offer only the latest version as a starter. Anyway we need to keep in mind that for many real components the demo and add-on itself might use very different Vaadin versions.

**Comment by mcollovati** [comment]
Personally, I would prefer the solution with separate modules for add-on code and tests/demo.
Since currently a V24 add-on template does not yet exist, I think we can change the structure.

On the other hand, we should perhaps provide some instructions on how to migrate V23 add-on previously created with the single module structure.

**Comment by samie** [comment]
Migration in this case is not very probable anyway. Once you start with one template you stick to that. However, I think ideally it should be just moving the code one level deeper and adding a demo: 
- parent/pom.xml
  - addon/pom.xml
  - demo/pom.xml
 
In this original setup the reference to the parent pom is was problematic since only the add-on should be distributed without the rest of the stuff. Maybe there are better options nowadays? I'm sure many want to use e.g. Maven release and versions plugins to maintain the project.

**Comment by mcollovati** [comment]
> In this original setup the reference to the parent pom is was problematic since only the add-on should be distributed without the rest of the stuff. Maybe there are better options nowadays? I'm sure many want to use e.g. Maven release and versions plugins to maintain the project.

Good point. If you want to publish only the add-on, with the multimodule structure, you need to flatten the pom file, so adding more configuration to the project.

At the end, I'll revert the changes to have `vaadin-core` with compile scope, as it does not seem so problematic and it simplifies DX

**Review by tltv — APPROVED** [review]

**Comment by mcollovati** [comment]
Thanks @tltv for the review.
If it is ok for everyone, I'll create a V24 protected branch with the contents of this PR

**Comment by mcollovati** [comment]
Closing as the v24 branch has been created, based on this PR

**Pull request closed without merging**
